### ISSUE TITLE
Event description is not selectable nor clickable on android

### ISSUE THREAD

**Issue by Claire-Couppie** [S-Stanley/eventus#103]
## Description of the issue

In the description of an event, I can read the event location and see the associated website but I cannot select the address nor click on the website url. Thus, I m unable to look for the location in a map application.

![eventus_issue](https://user-images.githubusercontent.com/11437215/178120224-542e04ac-5dad-4420-b2b6-b478f2d5a3cd.JPG)

## Potential solutions

- Redirect on maps when clicking on the address
- Add a "Copy" button
- Allow text selection
- Allow clicking on links
- Display a map in the event description page

**Comment by S-Stanley** [comment]
@Claire-Couppie thanks for your submission. I opened

- https://github.com/S-Stanley/eventus/issues/104
- https://github.com/S-Stanley/eventus/issues/106
